config/routes.rb
Rails.application.routes.draw do
  get 'admins/index'

  resources :items
  resources :admins

  root to: "items#index"

  get 'items/:id/next', to: "items#next_item" , as: 'next_item'
  get 'items/:id/prev', to: "items#prev_item" , as: 'prev_item'

  get 'admins/update_category', to: 'admins#update_category', as: "update_category"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article
  include Mongoid::Document
  field :name, type: String
  embedded_in :Comment
end

app/models/category.rb
class Category
  include Mongoid::Document
  field :name, type: String
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  field :content, type: String
  embeds_many :Article
end

app/models/image.rb
class Image
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  field :url, type: String
  field :path, type: String
  field :checksum, type: String
  field :status, type:String, default: '1'
  embedded_in :item
end

app/models/item.rb
class Item
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  field :category, type: String
  field :name, type: String
  field :description, type: String
  field :currency, type: String
  field :price, type: String
  field :item_id, type: String
  field :image_urls, type: String
  field :source, type: String
  field :page_id, type: String
  field :page_url, type: String
  field :tags, type: String
  field :status, type:String, default: "unchecked"
  embeds_many :images

  accepts_nested_attributes_for :images,  :autosave => true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def index

    # @categories = Category.all
    Category.delete_all
    @categories = Item.only(:category).distinct(:category)

    for i in @categories
      Category.create(name: i)
    end

  end

  def update_category
    # binding.pry
    Category.delete_all
    @categories = Item.only(:category).distinct(:category)

    for i in @categories
      Category.create(name: i)
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, except: [:index]
  def index

    @items = get_items_by_parameters(params)

    if !params[:page].blank?
      @items = @items.page(params[:page])
    else
      @items = @items.page(1)
    end

    if !params[:category].blank?
      @category = Category.find(params[:category])[:name]
    else
      @category = 'All Categories'
    end


    # render @items
  end

  def get_items_by_parameters(params)
    # binding.pry
    if !params[:category].blank?
      @category = Category.find(params[:category])
      if !@category.nil?
        @items = Item.where(category: @category[:name])
      end

    else
      @items = Item.all
    end

    if !params[:status].blank?
      if params[:status] == 'checked'
        @items = @items.where(status: 'checked')
      else
        @items = @items.where(:status.nin => ['checked', 'deleted'])
      end


    end

    @items.order_by(_id: 'asc')
  end

  def next_item
    # binding.pry
    @items = get_items_by_parameters({category: params[:category]})
    @item = @items.where('_id':{'$gt': params[:id]}).order_by(_id: 'asc').limit(1).first
    # respond_to do |format|
    #   format.html {render :edit}
    # end
    if !@item.blank?
      redirect_to proc { edit_item_path(@item, params: {category: params[:category]})} #, status: params[:status]
    else
      redirect_back fallback_location: :index
    end

  end

  def prev_item
    @items = get_items_by_parameters({category: params[:category]})
    @item = @items.where('_id':{'$lt': params[:id]}).order_by(_id: 'desc').limit(1).first
    if !@item.blank?
      redirect_to proc { edit_item_path(@item, params: {category: params[:category]})} #, status: params[:status]
    else
      redirect_back fallback_location: :index
    end
  end

  def show

  end

  def update
    # logger.info params
    # binding.pry
    # puts params
    respond_to do |format|
      # binding.pry
      if !@item.images.blank?
        params[:item][:images_attributes].each_pair{|k, v| @item.images.find(k).update(status: v['status'])}
      end
      @category = Category.find_by(name: params[:item][:category].to_s.remove(/[\[\]\"\"]/))
      if @item.update(status: "checked")
        @items = get_items_by_parameters({category: @category.id})  #status: params[:item][:status]
        @next_item = @items.where('_id':{'$gt': @item.id}).order_by(_id: 'asc').limit(1).first
        format.html{ redirect_to proc { edit_item_path(@next_item, params: {category: @category.id})}} #, status: params[:item][:status]
      end
    end
  end

  def destroy
    respond_to do |format|
      @category = Category.find_by(name: @item.category.to_s.remove(/[\[\]\"\"]/))
      if @item.update(status: "deleted")
        @items = get_items_by_parameters({category: @category.id})  #status: params[:item][:status]
        @next_item = @items.where('_id':{'$gt': @item.id}).order_by(_id: 'asc').limit(1).first

        format.html{ redirect_to proc { edit_item_path(@next_item, params: {category:  @category.id})}}
      end
    end
  end

  def edit
    # binding.pry
    @item.save

    if !@item.images.blank?
      i = 0
      len = @item.images.count
      until i < len
        @item.images[i].save
        puts item.images[i].id
        i+=1
      end
    end
    @category = params[:category]
    @status = params[:status]
	

  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:status, :category, images_attributes: [:status])
  end

  # def render_status
  #   if @item.status == 'unchecked'
  #     render :partial => '-'
  #   else
  #     render :partial => @item.status
  #   end
  # end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu
    @menu =  Category.all
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def render_status item
    if item.status == 'unchecked'
      return "-"
    else
      return item.status
    end
  end
end

app/views/admins/index.html.haml
%h1 Admins#index
%p Find me in app/views/admins/index.html.haml

-#%ul
-#  - @categories.each do |c|
-#    %li= c

-#= link_to 'Update Category', update_category_path(params: params)

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/items/edit.html.haml
%table.table.table-hover
  %thead

  %tbody
    -#-@item.images.each do |image|
    -#  %tr
    -#    %td= image._id
    -#    %td= image_tag image.url, class: 'img-rounded'
    -#    %td= image.status
    = link_to 'Previous', prev_item_path(@item,  params: params), class:'btn btn-primary'
    = link_to 'Next', next_item_path(@item, params: params), class: 'btn btn-primary'

    .form-container
      .page-header
      .form-elements
        = simple_form_for @item, method: :put do |f|
          %h3= @item.name.to_s.remove /[\[\]\"\"]/
          .text-danger
            %strong Status:
            =@item.status
          .text-info
            %strong Category:
            = @item.category.to_s.remove /[\[\]\"\"]/
          .text-info
            %strong Tag:
            = @item.tags.to_s.remove /[\[\]\"\"]/
          .text-info
            %strong Description:
            =@item.description.to_s.remove /[\[\]\"\"]/
          - @item.images.each do |i|
            = field_set_tag i._id do
              = f.simple_fields_for 'images_attributes[]', i do |fi|
                =image_tag i.url, class: 'img-rounded item_img'
                = f.hidden_field :category, value: @item.category
                = f.hidden_field :status, value: @item.status
                = fi.collection_radio_buttons :status, [[1, 'Ok'], [2, 'Archive'], [3,'Delete']], :first, :last do |b|
                  = b.label { b.radio_button + b.text }
          = f.submit 'Save', class: 'btn btn-success', params: params
          = link_to 'Delete', @item, method: :delete , data: { confirm: 'Are u sure?'},  class: 'btn btn-danger'


-#form_for @user do |f|
-#  f.collection_radio_buttons :rating, [[1, 'Bad'] ,[2, 'Ok'], [3, 'Great']],
-#  :first, :last, { item_wrapper_tag: false } do |b|
-#  b.radio_button + b.label(:class => "collection_radio_buttons icon-star")
-#  end
-#end

app/views/items/index.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title
      =@category

    =link_to "All", items_path(params: {category: params[:category]}), class: 'btn btn-primary'
    =link_to "checked", items_path(params: {status: 'checked', category: params[:category]}), class: 'btn btn-success'
    =link_to "unchecked", items_path(params: {status: 'unchecked', category: params[:category]}), class: 'btn btn-warning'
    .col-lg-1
      =paginate @items
  .panel-body
    %table.table.table-hover
      %thead
        %th Title
        %th No of images
        %th Status

      %tbody
        - @items.each do |item|
          %tr
            %td= item.name.to_s.remove /[\[\]\"\"]/
            %td= item.images.count
            %td= render_status item
            -#%td= link_to 'Show', item
            %td= link_to 'Edit', edit_item_path(item, params: {status: params[:status], category: params[:category]})
            %td= link_to 'Delete', item, method: :delete, data: {confirm: "sure?"}

  .panel-footer

app/views/items/show.html.haml
#{@item.title}



%table.table.table-hover
  %thead

  %tbody
    -@item.images.each do |image|
      %tr
        %td= image._id
        %td= image_tag image.url, class: 'img-rounded'

app/views/layouts/application.html.haml
-#<!DOCTYPE html>
-#<html>
-#  <head>
-#    <title>WiiLabel</title>
-#    <%= csrf_meta_tags %>
-#
-#    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
-#    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
-#  </head>
-#
-#  <body>
-#    <%= yield %>
-#  </body>
-#</html>
!!!
%html
  %head
    %title WiiLabel
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .row
      .col-md-9
        = yield
      .col-md-3
        %p
          .lead  Category
        .list-group
          - @menu = menu
          - @menu.each do |m|
            =link_to m[:name], items_path(params: {category: m[:id]}), class: 'list-group-item'
            -#= select_tag 'category_select', options_from_collection_for_select(@menu, :id, :name) ,:prompt => "Category..."